version: '3.8'

services:
  aisimpoker:
    build: .
    env_file: .env
    ports:
      - 5000:5000
  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - "6379:6379"